### ISSUE TITLE
snakemake error

### ISSUE THREAD

**Issue by Vishakha3118** [tkn-tub/dcc-env#2]
Hello All,

Whenever I run snakemake -jall to compile, I get the below error:

WorkflowError in line 18 of /home/suv2hi/Downloads/dcc-env-master/Snakefile:
Extensions for multiext may not contain path delimiters (/,\) and must start with '.' (e.g. .txt).
  File "/home/suv2hi/Downloads/dcc-env-master/Snakefile", line 18, in <module>

Kindly advise how to resolve it.

Omnet 5.6.2
Sumo 1.12.0

**Comment by dbuse** [comment]
Dear @Vishakha3118 

AFAIK this seems to be an issue with some particular snakemake versions. See https://github.com/snakemake-workflows/chipseq/issues/7 for example

As a quick fix, replace line 18 of `Snakefile` with:

```python
cpp=multiext("src/protobuf/veinsgym.pb", ".cc", ".h"),
```
