### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by serapergun** [tkn-tub/dcc-env#3]
Dear @dbuse 
When I try to build a model on DCC like below:

`def build_model(states, actions):
  
    model = tensorflow.keras.Sequential()  
    
    model.add(tensorflow.keras.layers.Reshape((1,), input_shape=(1,)))
    #model.add(Flatten(input_shape=(1,)))
    
    model.add(Dense(24, activation='relu', input_shape=(1,)))
   
    model.add(Dense(24, activation='relu'))
    
    model.add(Dense(actions, activation='linear'))
    #model.add(Flatten(input_shape=(states,1)))
    print("model.output_shape",model.output_shape)
    print("model.input_shape",model.input_shape)
    
    return model`

I got an error as:

`ValueError: Error when checking input: expected reshape_input to have 2 dimensions, but got array with shape (1, 1, 1)`

And then got this error:

`Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
malloc_consolidate(): unaligned fastbin chunk detected
Aborted (core dumped)`

Especially, for the ValueError I nearly spent 1 month and got no progress.
What should I do?
Regards,
Sorry for disturbing

**Comment by dbuse** [comment]
Dear @serapergun 
It looks lke your shape specifications are not correct. I suggest you check them in detail. As far as I can tell, the resulting shutdown error is a result of the reshape problem.
Closing this, as it apparently is not an issue of dcc-env.
